-- // Written by KingCreoo on October 14th, 2024
-- // Manages basic client functionality

-- // Services & Variables

local Players = game:GetService("Players")
local ReplicatedStorage = game:GetService("ReplicatedStorage")

local FunctionsFolder = ReplicatedStorage:WaitForChild("Functions")
--local LoadPlayerFunction = FunctionsFolder:WaitForChild("LoadPlayer")

-- // Local Functions

-- // Remote Functions
